### ISSUE TITLE
Documentation: How does respawn work?

### ISSUE THREAD

**Issue by lumodon** [DellAquila/HubTerminals#1]
Requesting update to description in https://ficsit.app/mod/2vsvqDggiD8G5k

> How does re-spawning upon death work if I create multiple Hub terminals?

**Comment by DellAquila** [comment]
Great lumodon... I just add there... 

You will still respawn in the vanilla hub.

**Comment by lumodon** [comment]
Thank you. Simple and straight forward 💯
